### ISSUE TITLE
[BUG] Повторяющиеся статьи

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [Ninja-Official/rtu-mirea-news-api#2]
**Описание ошибки**
15 одинаковых статей подряд в разделе новости в Mirea App

**Ожидаемое поведение**
1 уникальная статья

**Скриншоты**
![D9EF4153-A887-41B0-A7FF-1B11838E3DE1](https://user-images.githubusercontent.com/70258211/131077220-869ef200-cad7-4d37-b29a-bd3cd83c8726.png)
![349AABA4-BAD1-430F-9455-92B1A431656E](https://user-images.githubusercontent.com/70258211/131077227-8cdaf7e1-3d34-455f-b7d9-c12c869adc9e.png)

**Comment by Shmyaks** [comment]
Следим за ситуацией дальше. В случае возникновение, пожалуйста, откройте issues ещё раз. Спасибо!

**Comment by 0niel** [comment]
Проблема была связана с опечатками в заголовках новостей и исправлением их. Исправлено в https://github.com/Ninja-Official/rtu-mirea-news-api/commit/489bf7b80ed3e505d86ce87e4cd3a3181d204bbf. Спасибо!

**Comment by ValeryVerkhoturov** [comment]
> Проблема была связана с опечатками в заголовках новостей и исправлением их. Исправлено в [489bf7b](https://github.com/Ninja-Official/rtu-mirea-news-api/commit/489bf7b80ed3e505d86ce87e4cd3a3181d204bbf). Спасибо!


![EBE3CC8A-209C-455E-A302-7E4B2B74AFA8](https://user-images.githubusercontent.com/70258211/131617438-15b40e7c-6459-4cca-a4a1-082317ff078b.png)

**Comment by 0niel** [comment]
Исправлено (надеюсь) в https://github.com/Ninja-Official/rtu-mirea-news-api/commit/85d329e9e980b900e6066bcde05bc8555dfd4799

**Comment by ValeryVerkhoturov** [comment]
> Исправлено (надеюсь) в [85d329e](https://github.com/Ninja-Official/rtu-mirea-news-parser/commit/85d329e9e980b900e6066bcde05bc8555dfd4799)

Подряд повторяющиеся статьи:
![061A361C-F221-4EB4-AC35-71DC24D9CCBB](https://user-images.githubusercontent.com/70258211/153017893-644ae00d-b1f1-41fe-9247-53e5ee7663ab.png)

Не подряд повторяющие статьи:
![39BF937D-A2EC-4816-94E1-2BFF8955E9EF](https://user-images.githubusercontent.com/70258211/153018467-72f8170c-5395-45fe-88fc-84e57129bc1a.png)

**Comment by 0niel** [comment]
Исправлено в https://github.com/mirea-ninja/rtu-mirea-news-parser/commit/0ec9952a392711704508dcbc50bc1aa32e8d3eb9

Добавил токенизацию и сравнение токенов текста. Также сделал сравнение новостей по заголовкам.
